FirstMvcApp/Controllers/ArticlesController.cs
using System.Collections.Concurrent;
using System.Diagnostics;
using AutoMapper;
using FirstMvcApp.Core.DTOs;
using FirstMvcApp.Core.Interfaces;
using FirstMvcApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FirstMvcApp.Controllers
{
    [Authorize(Roles = "User, Admin")]
    public class ArticlesController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IConfiguration _configuration;
        private readonly ILogger<ArticlesController> _logger;
        private readonly IArticlesService _articlesService;
        private readonly ISourceService _sourceService;
        private readonly IRssService _rssService;
        private readonly IHtmlParserService _htmlParserService;

        private readonly int _pageSize;

        public ArticlesController(IMapper mapper,
            IArticlesService articlesService,
            ILogger<ArticlesController> logger, IConfiguration configuration,
            ISourceService sourceService, IRssService rssService, IHtmlParserService htmlParserService)
        {
            _mapper = mapper;
            _articlesService = articlesService;
            _logger = logger;
            _configuration = configuration;
            _sourceService = sourceService;
            _rssService = rssService;
            _htmlParserService = htmlParserService;
            //_newsService = newsService;`
            _pageSize = Convert.ToInt32(_configuration["ApplicationVariables:PageSize"]);
        }


        [HttpGet]
        public async Task<IActionResult> Index(int page = 1)
        {
            var pageAmount = Convert.ToInt32(
                Math.Ceiling(
                    (double)(await _articlesService.GetAllNewsAsync()).Count() / _pageSize));
            var articles = (await _articlesService.GetNewsByPageAsync(page - 1))
                .Select(article => _mapper.Map<ArticleListItemViewModel>(article))
                .OrderByDescending(article => article.CreationDate).ToList();

            var model = new ArticleIndexViewModel()
            {
                ArticleList = articles,
                PagesAmount = pageAmount
            };

            return View(model);
        }



        [HttpGet]
        public async Task<IActionResult> Table()
        {
            var articles =
                (await _articlesService.GetAllNewsAsync())
                .Select(a => _mapper.Map<ArticleTableViewModel>(a))
                .ToArray();


            return View(articles);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var article = await _articlesService.GetArticleAsync(id);
            var sources = await _sourceService.GetSourcesForDropdownSelect();

            var viewModel = _mapper.Map<ArticleChangeModel>(article);
            viewModel.Sources = sources
                .Select(dto => new SelectListItem(dto.Name,
                    dto.Id.ToString("D"),
                    dto.Id.Equals(article.SourceId)))
                .ToList();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ArticleChangeModel model)
        {

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Search([FromBody]SearchArticlesModel model)
        {
            var searchData = (await _articlesService
                .GetArticlesByNameAsync(model.SearchText))
                .Select(article => _mapper.Map<ArticleListItemViewModel>(article))
                .OrderByDescending(article => article.CreationDate).ToList();

            return View("SearchPartial", searchData);
        }

        [HttpPost]
        public async Task<IActionResult> SearchAPI([FromBody] SearchArticlesModel model)
        {
            var searchData = (await _articlesService
                    .GetArticlesByNameAsync(model.SearchText))
                .Select(article => _mapper.Map<ArticleListItemViewModel>(article))
                .OrderByDescending(article => article.CreationDate).ToList();

            return Ok(searchData);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var article = await _articlesService.GetArticleWithAllNavigationProperties(id);

            if (article == null)
                return BadRequest("Incorrect id");

            var viewModel = new NewsDetailViewModel
            {
                //Comments = article.Comments
                //    .Select(comment => new CommentModel()
                //    {
                //        Id = comment.Id,
                //        Text = comment.Text,
                //        CreationDate = comment.CreationDateTime,
                //        UserName = comment.User.Email
                //    })
                //    .OrderBy(model => model.CreationDate)
                //    .ToList(),
                NewsDetailModel = new NewsDetailModel()
                {
                    Id = article.Id,
                    //SourceName = article.Source.Name,
                    Body = article.Body,
                    Title = article.Title,
                    CreationDate = article.CreationDate
                }
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var newsDetailModel = new NewsDetailModel();
            return View(newsDetailModel);
        }

        //[HttpPost]
        //public async Task<IActionResult> Create(NewsDetailModel model)
        //{
        //    //is sourse is correct
        //    if (!string.IsNullOrEmpty(model.SourceName))
        //    {
        //        var sourse = await _db.Sources.FirstOrDefaultAsync(source => source.Name.Equals(model.SourceName));
        //        if (sourse != null)
        //        {
        //            //check fields for null
        //            var entity = new Article()
        //            {
        //                Id = Guid.NewGuid(),
        //                Body = model.Body,
        //                Description = model.Body,
        //                CreationDate = DateTime.Now,
        //                Title = model.Title,
        //                SourceId = sourse.Id
        //            };
        //        }
        //    }


        //    //todo insert to db
        //    return BadRequest();
        //}
        //[HttpGet]
        //public async Task<IActionResult> Edit(Guid id)
        //{
        //    var article = await _db.Articles
        //        .AsNoTracking()
        //        .FirstOrDefaultAsync(article 
        //            => article.Id.Equals(id));

        //    if (article != null)
        //    {
        //        var model = new NewsDetailModel()
        //        {
        //            Id = id,
        //            Body = article.Body,
        //            Title = article.Title,
        //            CreationDate = article.CreationDate
        //        };
        //        return View(model);
        //    }

        //    return BadRequest();
        //}

        //[HttpPost]
        //public async Task<IActionResult> Edit(NewsDetailModel model)
        //{


        //    return BadRequest();
        //}

        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            var deleteModel = new DeleteModel() { Id = id };
            return View(deleteModel);
        }

        [HttpPost]
        public IActionResult Delete(DeleteModel model)
        {

            _articlesService.DeleteAsync(model.Id);
            return RedirectToAction("Table");
        }

        [HttpPost, ActionName("DeleteExample")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteExamplePost(DeleteModel model)
        {
            var deleteResult = await _articlesService.DeleteAsync(model.Id);

            if (deleteResult == null)
                return BadRequest();


            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> GetNewsFromSources()
        {
            try
            {
                var sw = new Stopwatch();
                sw.Start();
                var rssUrls = await _sourceService.GetRssUrlsAsync();
                var concurrentDictionary = new ConcurrentDictionary<string, RssArticleDto?>();

                var result = Parallel.ForEach(rssUrls, parallelOptions: new ParallelOptions() { }, dto =>
                    {
                        _rssService.GetArticlesInfoFromRss(dto.RssUrl).AsParallel().ForAll(articleDto
                            => concurrentDictionary.TryAdd(articleDto.Url, articleDto));
                    });

                var extArticlesUrls = await _articlesService.GetAllExistingArticleUrls();

                Parallel.ForEach(extArticlesUrls.Where(url => concurrentDictionary.ContainsKey(url)),
                    s => concurrentDictionary.Remove(s, out var dto));

                //var groupedRssArticles = concurrentDictionary.GroupBy(pair => _sourceService.GetSourceByUrl(pair.Key).Result);

                //Parallel.ForEach(groupedRssArticles,)


                foreach (var rssArticleDto in concurrentDictionary)
                {
                    var body = await _htmlParserService.GetArticleContentFromUrlAsync(rssArticleDto.Key);
                }


                sw.Stop();
                return Ok();
            }
            catch (Exception ex)
            {
                var exMessage =
                    string.Format(_configuration.GetSection("ApplicationVariables")["LogErrorMessageFormat"],
                        ex.Message,
                        ex.StackTrace);
                _logger.LogError(ex, exMessage);
                return StatusCode(500, new { ex.Message });
            }

FirstMvcApp/Views/Articles/ArticlePreviewPartial.cshtml
@model ArticleListItemViewModel

<div class="col-12">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">@Model.Title</h5>
            <p class="card-text">@Model.Description</p>
            <a asp-action="Details" asp-route-id="@Model.Id" asp-fragment="" class="btn btn-primary">Read</a>
            <article-buttons-block>
                <a class="btn btn-warning" asp-controller="Articles" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                <a class="btn btn-danger" asp-controller="Articles" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
            </article-buttons-block>
            @*<a asp-controller="User" asp-action="UserDetail" asp-route-model="@{ new UserRegisterModel() { };}" class="btn btn-primary">Read</a>*@
        </div>
        <div class="card-footer text-muted">
            Published: @Model.CreationDate
        </div>
    </div>
</div>


@*///domain/smth/smth#smth1*@

FirstMvcApp/Views/Articles/ArticlesPagination.cshtml
@model int 
<div class="btn-toolbar mb-3" role="toolbar">
    <div class="btn-group me-2" role="group">
        @for (int i = 1; i <= Model; i++)
        {
            <a asp-controller="Articles" asp-action="Index" asp-route-page="@i" class="btn btn-outline-secondary">
                @i
            </a>
        }
    </div>
</div>

FirstMvcApp/Views/Articles/Create.cshtml
@model NewsDetailModel

@{
    ViewBag.Title = "Edit";
    Layout = "_Layout";
}
<div class="container">
    <h2>Edit article</h2>
    <div class="row gx-5">
        <form asp-controller="Articles" asp-action="Edit" asp-antiforgery="true" method="post"> 
            <div>
                <input type="hidden" asp-for="Id"/>
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label" asp-for="Title"></label>
                    <input class="form-control" type="text" asp-for="Title">
                </div>
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label" asp-for="Body"></label>
                    <textarea class="form-control" asp-for="Body"></textarea>
                </div> 
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label" asp-for="ArticleType"></label>
                    <select asp-for="ArticleType" asp-items="Html.GetEnumSelectList<ArticleType>()"></select>
                </div>
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label" asp-for="CreationDate"></label>
                    <input type="datetime-local" class="form-control" asp-for="CreationDate">
                </div>
            </div>
        </form>
    </div>
</div>

FirstMvcApp/Views/Articles/Delete.cshtml
@model DeleteModel

<div class="container">
    <p class="lead">
        Are you sure that you want delete article @Model.Id?
    </p>
    
    <form asp-controller="Articles" asp-action="Delete" method="post">
        <input asp-for="Id" type="hidden"/>
        <a asp-action="Table" asp-controller="Articles" class="btn btn-primary" >Cancel</a>
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>

FirstMvcApp/Views/Articles/Details.cshtml
@model NewsDetailViewModel

<div class="container">
   
    <div class="row gx-5">
        <div class="card" >
            <div class="card-body">
                <h1 class="card-title">@Model.NewsDetailModel.Title</h1>
                <h6 class="card-subtitle mb-2 text-muted">@Model.NewsDetailModel.CreationDate</h6>
                <div class="card-text">
                    @Html.Raw(Model.NewsDetailModel.Body)
                </div>
              
            </div>
        </div>
       @* <div class="col-3">
            <h1></h1>
        </div>
        <div class="offset-6 col-3">
            <p>
                @Model.NewsDetailModel.SourceName
            </p>
            <p>
                @Model.NewsDetailModel.CreationDate
            </p>
        </div>
        <br/>
        <div class="col-12">
          
        </div>*@
        <br/>

        <div class="col-12">
            Date Time now: @DateTime.Now.ToString("F")
        </div>

        <cache expires-on="DateTimeOffset.Now.AddDays(1)">
            <div class="col-12">
                @await Html.PartialAsync("DateTimePartial")
            </div>
        </cache>
    </div>
    <hr/>
    @*<a asp-controller="Articles" asp-action="Edit" asp-route-id="@Model.NewsDetailModel.Id">Edit</a>*@
    <hr/>
    @* <div class="row gx-5">
        @foreach (var comment in Model.Comments)
        {
            <div class="offset-2 col-8">
                <div class="card">
                    <h5 class="card-title">@comment.UserName</h5>
                    <div class="card-body">
                        @comment.Text
                    </div>
                    <div class="card-footer text-muted">
                        Published: @comment.CreationDate
                    </div>
                </div>
            </div>
        }
        <hr />

    </div>*@
</div>

FirstMvcApp/Views/Articles/Edit.cshtml
@model ArticleChangeModel

@{
    ViewBag.Title = "Edit";
    Layout = "_Layout";
}
<div class="container">
    <h2>Edit article</h2>
    <div class="row gx-5">
        <form asp-controller="Articles" asp-action="Edit" asp-antiforgery="true" method="post"> 
                <input type="hidden" asp-for="Id"/>
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label" asp-for="Title"></label>
                    <input class="form-control" type="text" asp-for="Title">
                </div>
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label" asp-for="Title"></label>
                    <textarea class="form-control" asp-for="Description"></textarea>
                </div>
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label" asp-for="Body"></label>
                    <textarea class="form-control" asp-for="Body"></textarea>
                </div> 
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label" asp-for="SourceId"></label>
                    <select asp-for="SourceId" asp-items="Model.Sources"></select>
                </div>
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label" asp-for="CreationDate"></label>
                    <input type="datetime-local" class="form-control" asp-for="CreationDate">
                </div> 
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label" asp-for="PositivityRate"></label>
                    <input type="number" class="form-control" asp-for="PositivityRate">
                </div> 
                <div class="mb-3">
                    @Html.DropDownListFor(model => model.SourceId, Model?.Sources, "Select category")
                </div> 
                <input type="submit" class="btn btn-primary" value="Submit">

        </form>
    </div>
</div>

FirstMvcApp/Views/Articles/GetArticlesPartial.cshtml
<div class="row g-5">
    <div class="col-4 offset-4 g-5">
        <form asp-controller="Articles" asp-action="GetNewsFromSources" method="post">
            <input class="btn btn-primary" type="submit" value="GET NEWS"/>
        </form>
    </div>
</div>

FirstMvcApp/Views/Articles/Index.cshtml
@model ArticleIndexViewModel

@*<form method="post" action="~/news/generate">

    <input type="text" name="name" placeholder="name"/>
    <input type="number" name="id" placeholder="id"/>
    <input type="radio" name="isApproved" value="false"/>
    <input type="submit" value="Submit"/>

</form>*@
 

<div class="container g-5">
    @*@if (Model.IsAdmin)
    {
        @Html.RenderPartialAsync("GetArticlesPartial")
    }*@
    
  @*  @await Html.PartialAsync("GetArticlesPartial")
*@
    <get-news-button></get-news-button>
    


    <div class="mb-3 row">
        <div class="col-sm-11">
            <input type="text" name="searchText" class="form-control" id="search-article-text">
        </div>
        <div class="col-sm-1">
            <button type="submit" class="btn btn-primary mb-3" id="search-article-btn">Search</button>
        </div>
    </div>
       <div id="spinner" class="spinner-border" role="status" hidden>
            <span class="visually-hidden">Loading...</span>
        </div>
    <div class="row g-5" id="articles-list">
     
        @foreach (var article in Model.ArticleList)
        {
            await Html.RenderPartialAsync("ArticlePreviewPartial", article);
        }
    </div>
</div>

@section Pagination
{
    @await Html.PartialAsync("Pagination", new PaginationModel {PagesAmount = Model.PagesAmount, ControllerName = "Articles",ActionName = "Index" })
}

@section Scripts
{
    <script src="~/js/article.js" ></script>
}

FirstMvcApp/Views/Articles/SearchPartial.cshtml
@model List<ArticleListItemViewModel>
@{
    Layout = null;
}

<div class="row g-5" id="articles-list">
    @foreach (var article in Model)
    {
        await Html.RenderPartialAsync("ArticlePreviewPartial", article);
    }
</div>

FirstMvcApp/Views/Articles/Table.cshtml
@model ArticleTableViewModel[]

<div class="container">
    <div class="row">
        <table class="table col-12">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Title</th>
                    <th scope="col">Rate</th>
                    <th scope="col">Creation Date</th>
                    <th scope="col">#</th>
                </tr>
            </thead>
            <tbody>
            
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.Title</td>
                    <td>@item.Rate</td>
                    <td>@item.CreationDate</td>
                    <td>

                        <button type="button" class="btn btn-outline-secondary" onclick="delete(@item.Id)">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                            </svg>
                            <span class="visually-hidden">Button</span>
                        </button>
                    </td>
                </tr>
            }
        
            </tbody>
        </table>
    </div>
</div>

FirstMvcApp/Views/Articles/TopRated.cshtml
@model List<ArticleListItemViewModel>

@*<form method="post" action="~/news/generate">

    <input type="text" name="name" placeholder="name"/>
    <input type="number" name="id" placeholder="id"/>
    <input type="radio" name="isApproved" value="false"/>
    <input type="submit" value="Submit"/>

</form>*@
 

<div class="container">
    <div class="row">
    @foreach (var article in Model)
    {
        await Html.RenderPartialAsync("ArticlePreviewPartial", article);
    }
    </div>
</div>